version: "3.7"
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "$RABBITMQUSERNAME"
      RABBITMQ_DEFAULT_PASS: "$RABBITMQPASSWORD"
    ports:
      - $DEFAULT_RABBITMQ_LOCAL_PORT:$DEFAULT_RABBITMQ_DOCKER_PORT
      - $MANAGEMENT_RABBITMQ_UI_LOCAL_PORT:$MANAGEMENT_RABBITMQ_UI_DOCKER_PORT
    networks:
      - my-net

  mysqldb:
    build: ./
    image: "mysql:latest"
    restart: always
    env_file: ./.env
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    networks:
      - my-net
    environment:
      MYSQL_DATABASE: "$MYSQLDB_DATABASE"
      MYSQL_USER: "$MYSQLDB_USER"
      MYSQL_PASSWORD: "$MYSQLDB_PASSWORD"
      MYSQL_ROOT_PASSWORD: "$MYSQLDB_ROOT_PASSWORD"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql

  api_service:
    build: ./users/
    restart: always
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    networks:
      - my-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: "$MYSQLDB_USER"
      SPRING_DATASOURCE_PASSWORD: "$MYSQLDB_PASSWORD"
      SPRING_DDL-AUTO: update
      SERVER_PORT: 8082
      HOST_SMTP: "$HOST_SMTP"
      PORT_SMTP: $PORT_SMTP
      USER_SMTP: "$USER_SMTP"
      PASSWORD_SMTP: "$PASSWORD_SMTP"
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: $DEFAULT_RABBITMQ_DOCKER_PORT
      RABBITMQ_USERNAME: "$RABBITMQUSERNAME"
      RABBITMQ_PASSWORD: "$RABBITMQPASSWORD"
      RABBITMQ_QUEUE: "$RABBITMQQUEUE"
      RABBITMQ_EXCHANGE: "$RABBITMQEXCHANGE"
      RABBITMQ_ROUTING_KEY: "$RABBITMQROUTINGKEY"
    depends_on:
      - mysqldb
      - rabbitmq
    volumes:
      - .m2:/root/.m2 

  consumer_service:
      build: ../CLIENT/consumer/
      restart: always
      env_file: ./.env
      ports:
        - $CONSUMER_LOCAL_PORT:$CONSUMER_DOCKER_PORT
      networks:
        - my-net
      environment:
        RABBITMQ_HOST: rabbitmq
        RABBITMQ_PORT: $DEFAULT_RABBITMQ_DOCKER_PORT
        RABBITMQ_USERNAME: "$RABBITMQUSERNAME"
        RABBITMQ_PASSWORD: "$RABBITMQPASSWORD"
        RABBITMQ_QUEUE: "$RABBITMQQUEUE"
        RABBITMQ_EXCHANGE: "$RABBITMQEXCHANGE"
        RABBITMQ_ROUTING_KEY: "$RABBITMQROUTINGKEY"
      depends_on:
        - rabbitmq
        - api_service
        
      healthcheck:
        test: ["CMD", "rabbitmqadmin", "-H", "rabbitmq", "-P", "5672", "list", "queues", "|", "grep", "$RABBITMQ_QUEUE"]
        interval: 10s  # Check every 10 seconds
        timeout: 5s     # Wait up to 5 seconds for response
        retries: 5     # Retry up to 5 times before considering unhealthy

      
networks:
  my-net: