FROM debian:bullseye-slim

# Instala Python y wget
# Instala Python, wget, y python3-venv

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    python3-venv \
    openjdk-11-jre-headless \
    openssh-server \
    nano \
    wget \
    && rm -rf /var/lib/apt/lists/* \
    dos2unix

# Instala allure commandline
RUN wget -O allure-2.14.0.tgz https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.14.0/allure-commandline-2.14.0.tgz && \
    tar -zxvf allure-2.14.0.tgz -C /opt/ && \
    ln -s /opt/allure-2.14.0/bin/allure /usr/bin/allure && \
    rm allure-2.14.0.tgz

RUN echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
RUN echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config


WORKDIR /app

COPY . .

# Asegura que run.sh tenga permisos de ejecución

RUN chmod +x ./run.sh
RUN chmod +x ./llave.sh

# Mantén el contenedor abierto
CMD ["sh", "-c", "apt-get update && apt-get install dos2unix -y && dos2unix ./run.sh && dos2unix ./llave.sh && bash ./llave.sh && tail -f /dev/null"]
