USE api_logs;

DROP TABLE IF EXISTS logs;

CREATE TABLE logs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    tipo VARCHAR(255),
    aplicacion VARCHAR(255),
    clase_modulo VARCHAR(255),
    resumen VARCHAR(255),
    descripcion VARCHAR(255)
);