# Usa la imagen oficial de Python 3 como base
FROM python:3.9-bullseye

# Instalar curl, para pruebas
#RUN apk add curl

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia los archivos necesarios al contenedor
COPY . .

# Instala las dependencias de la aplicación
RUN pip install -r requirements.txt

# Ejecuta la aplicación cuando se inicie el contenedor
CMD ["python", "init.py"]
